name: NASA Project CI
on:
  push:
    branches: [ nasa_project, test_api, node_performance, database]
  pull_request:
    branches: [ master, nasa_project, test_api, node_performance, database]
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List files
        run: ls -R
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install server dependencies
        run: npm run install-server
        working-directory: NASA
      - name: Install client dependencies
        run: npm run install-client
        working-directory: NASA
      - name: Build client
        run: npm run build --prefix client
        working-directory: NASA